---
name: Clean PR checks

'on':
  workflow_dispatch:
    inputs:
      pr:
        description: PR to be cleaned
        required: true
      checks:
        description: Checks to be cleaned
        required: true
        default: >-
          build/alidist/O2Suite/o2/macOS-arm
          build/O2/alidist-dataflow-cs8
          build/O2/alidist-cs8
          build/AliGenerators/generators
          build/AliRoot/alidist
          build/O2/alidist
          build/O2/alidist-dataflow
          build/alidist/O2Suite/o2/macOS
          build/O2/fullCI/alidist
      owner:
        description: Organization
        required: true
        default: 'alisw'
      repo:
        description: Repository
        required: true
        default: 'alidist'

jobs:
  cleanup_pr_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install ali-bot
        run: |
          sudo apt-get update
          sudo apt-get install libsasl2-dev python-dev libldap2-dev libssl-dev
          python3 -m pip install git+https://github.com/alisw/ali-bot@master

      - uses: octokit/graphql-action@v2.x
        id: last_commit
        with:
          query: |
            query latest_commit($owner: String!, $repo: String!, $pull: Int!) {
              repository(owner: $owner, name: $repo) {
                pullRequest(number: $pull) {
                  commits(last: 1) {
                    nodes {
                      commit {
                        oid
                      }
                    }
                  }
                }
              }
            }
          owner: ${{ github.event.inputs.owner }}
          repo: ${{ github.event.inputs.repo }}
          pull: ${{ github.event.inputs.pr }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup tests
        run: |
          set -x
          for check in ${CHECKS//,/ }; do
            set-github-status -c "$REPO@$COMMIT" -s "$check/pending"
          done
        env:
          CHECKS: ${{ github.event.inputs.checks }}
          REPO: ${{ github.event.inputs.owner }}/${{ github.event.inputs.repo }}
          COMMIT: ${{ fromJSON(steps.last_commit.outputs.data).repository.pullRequest.commits.nodes[0].commit.oid }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
